import type { FashionProfile, Product, Retailer } from "./types";

export const demoProfile: FashionProfile = {
  label: "My Fashion Passport",
  country: "UK",
  size: "UK 10",
  heightCm: 163,
  colourSeason: "Deep Winter",
  bodyShape: "Inverted triangle",
  budget: 100,
  colours: {
    love: ["Red", "Burnt orange", "Terracotta", "Jewel tones", "Dark pink", "Camel"],
    avoid: ["Olive", "Grey", "Taupe"],
  },
  silhouettes: { love: ["Flowy", "A-line", "Fit and flare"], avoid: ["Boxy", "Structured"] },
  necklines: { love: ["Square", "Boat", "Scoop"], avoid: ["Cowl"] },
  sleeves: { love: ["Long", "3/4", "Sleeveless"], avoid: ["Cap"] },
  patterns: { love: ["Ditsy", "Gingham", "Plaid", "Solid"], avoid: ["Large print", "Animal"] },
  materials: { love: ["Chiffon", "Silk", "Pure cotton", "Linen"], avoid: ["Polyester"] },
  lengths: { love: ["Midi"], avoid: [] },
  retailers: { love: ["John Lewis", "ASOS", "Next", "Zara", "Mango"], avoid: ["Primark", "Shein", "Temu"] },
};

export const retailers: Retailer[] = [
  { id: "asos", name: "ASOS", url: "https://www.asos.com/women/dresses/cat/?cid=8799", kind: "retailer" },
  { id: "next", name: "Next", url: "https://www.next.co.uk/shop/womens/clothing/dresses", kind: "retailer" },
  { id: "jigsaw", name: "Jigsaw", url: "https://www.jigsaw-online.com/collections/dresses", kind: "shopify" },
  { id: "jovonna", name: "Jovonna", url: "https://jovonnalondon.com/collections/dresses-fp", kind: "shopify" },
  { id: "vinted", name: "Vinted", url: "https://www.vinted.co.uk/", kind: "secondhand" },
  { id: "johnlewis", name: "John Lewis", url: "https://www.johnlewis.com/browse/women/womens-dresses/_/N-flw", kind: "retailer" },
];

export const tasteProducts: Product[] = [
  { id: "p1", retailerId: "asos", name: "Satin square-neck midi dress", brand: "ASOS Design", price: 58, colour: "Dark pink", hex: "#A81955", silhouette: "Fit and flare", neckline: "Square", sleeve: "Long", pattern: "Solid", material: "Silk", length: "Midi", sizes: ["UK 8", "UK 10", "UK 12"] },
  { id: "p2", retailerId: "asos", name: "Ditsy chiffon tea dress", brand: "Never Fully Dressed", price: 92, colour: "Jewel tones", hex: "#173F4F", silhouette: "A-line", neckline: "Scoop", sleeve: "3/4", pattern: "Ditsy", material: "Chiffon", length: "Midi", sizes: ["UK 10", "UK 12", "UK 14"], accent: "#D13A69" },
  { id: "p3", retailerId: "asos", name: "Soft drape cowl midi", brand: "Selected", price: 76, colour: "Grey", hex: "#98999B", silhouette: "Flowy", neckline: "Cowl", sleeve: "Sleeveless", pattern: "Solid", material: "Polyester", length: "Midi", sizes: ["UK 8", "UK 10"] },
  { id: "p4", retailerId: "asos", name: "Linen gingham sundress", brand: "Reclaimed Vintage", price: 64, colour: "Red", hex: "#B62B35", silhouette: "A-line", neckline: "Square", sleeve: "Sleeveless", pattern: "Gingham", material: "Linen", length: "Midi", sizes: ["UK 6", "UK 8", "UK 10", "UK 12"], accent: "#F6E9D9" },
  { id: "p5", retailerId: "next", name: "Cotton boat-neck day dress", brand: "Next", price: 46, colour: "Camel", hex: "#B47A4E", silhouette: "Fit and flare", neckline: "Boat", sleeve: "3/4", pattern: "Solid", material: "Pure cotton", length: "Midi", sizes: ["UK 10", "UK 12", "UK 14"] },
  { id: "p6", retailerId: "next", name: "Terracotta linen wrap dress", brand: "Love & Roses", price: 78, colour: "Terracotta", hex: "#B5543C", silhouette: "Flowy", neckline: "Scoop", sleeve: "Long", pattern: "Solid", material: "Linen", length: "Midi", sizes: ["UK 8", "UK 10", "UK 12"] },
  { id: "p7", retailerId: "next", name: "Olive utility shift dress", brand: "Friends Like These", price: 52, colour: "Olive", hex: "#72704B", silhouette: "Boxy", neckline: "Boat", sleeve: "Cap", pattern: "Solid", material: "Pure cotton", length: "Mini", sizes: ["UK 8", "UK 10"] },
  { id: "p8", retailerId: "jigsaw", name: "Jewel silk pleated dress", brand: "Jigsaw", price: 98, colour: "Jewel tones", hex: "#315A64", silhouette: "A-line", neckline: "Boat", sleeve: "Sleeveless", pattern: "Solid", material: "Silk", length: "Midi", sizes: ["UK 10", "UK 12"] },
  { id: "p9", retailerId: "jovonna", name: "Ruby scoop-neck midi", brand: "Jovonna London", price: 89, colour: "Red", hex: "#9E2632", silhouette: "Fit and flare", neckline: "Scoop", sleeve: "Long", pattern: "Solid", material: "Chiffon", length: "Midi", sizes: ["UK 8", "UK 10"] },
  { id: "p10", retailerId: "vinted", name: "Pre-loved plaid midi dress", brand: "Mango", price: 28, colour: "Dark pink", hex: "#74384E", silhouette: "A-line", neckline: "Square", sleeve: "3/4", pattern: "Plaid", material: "Pure cotton", length: "Midi", sizes: ["UK 10"], accent: "#E9B8A7" },
  { id: "p11", retailerId: "johnlewis", name: "Burnt orange linen midi", brand: "Whistles", price: 95, colour: "Burnt orange", hex: "#C35E2D", silhouette: "Flowy", neckline: "Square", sleeve: "Sleeveless", pattern: "Solid", material: "Linen", length: "Midi", sizes: ["UK 8", "UK 10", "UK 12"] },
  { id: "p12", retailerId: "johnlewis", name: "Taupe animal-print column dress", brand: "Phase Eight", price: 99, colour: "Taupe", hex: "#8B7969", silhouette: "Structured", neckline: "Cowl", sleeve: "Cap", pattern: "Animal", material: "Polyester", length: "Maxi", sizes: ["UK 10", "UK 12"] },
];

// Verified public catalogue snapshots retrieved on 1 September 2026.
// Images remain hosted by their retailers and every card links to the real item.
export const products: Product[] = [
  { id:"asos-210130178", retailerId:"asos", name:"Topshop chiffon floral print frill one shoulder maxi dress in green", brand:"Topshop", price:75, colour:"Green", hex:"#536d46", silhouette:"Flowy", neckline:"Asymmetric", sleeve:"Sleeveless", pattern:"Large print", material:"Chiffon", length:"Maxi", sizes:[], imageUrl:"https://images.asos-media.com/products/topshop-chiffon-floral-print-frill-one-shoulder-maxi-dress-in-green/210130178-1-green", productUrl:"https://www.asos.com/prd/210130178", source:"live-snapshot" },
  { id:"asos-211546993", retailerId:"asos", name:"ASOS DESIGN satin shoulder pad maxi dress in chocolate", brand:"ASOS DESIGN", price:60, colour:"Brown", hex:"#5e4438", silhouette:"Structured", neckline:"Scoop", sleeve:"Sleeveless", pattern:"Solid", material:"Not stated", length:"Maxi", sizes:[], imageUrl:"https://images.asos-media.com/products/asos-design-satin-shoulder-pad-maxi-dress-in-chocolate/211546993-1-chocolate", productUrl:"https://www.asos.com/prd/211546993", source:"live-snapshot" },
  { id:"asos-210486268", retailerId:"asos", name:"Topshop organza bubble hem mini dress in black", brand:"Topshop", price:55, colour:"Black", hex:"#171717", silhouette:"Fit and flare", neckline:"Scoop", sleeve:"Sleeveless", pattern:"Solid", material:"Not stated", length:"Mini", sizes:[], imageUrl:"https://images.asos-media.com/products/topshop-organza-bubble-hem-mini-dress-in-black/210486268-1-black", productUrl:"https://www.asos.com/prd/210486268", source:"live-snapshot" },
  { id:"asos-211562115", retailerId:"asos", name:"ASOS DESIGN printed mesh floral dropped waist mini dress in chartreuse", brand:"ASOS DESIGN", price:45, colour:"Yellow", hex:"#b3ad37", silhouette:"Flowy", neckline:"Tie neck", sleeve:"Long", pattern:"Large print", material:"Not stated", length:"Mini", sizes:[], imageUrl:"https://images.asos-media.com/products/asos-design-printed-mesh-floral-dropped-waist-blouson-tie-neck-mini-dress-in-chartreuse/211562115-1-yellowfloral", productUrl:"https://www.asos.com/prd/211562115", source:"live-snapshot" },
  { id:"asos-211657548", retailerId:"asos", name:"Bershka strappy floral maxi dress in yellow", brand:"Bershka", price:45.99, colour:"Yellow", hex:"#d4bf43", silhouette:"A-line", neckline:"Square", sleeve:"Sleeveless", pattern:"Large print", material:"Not stated", length:"Maxi", sizes:[], imageUrl:"https://images.asos-media.com/products/bershka-strappy-floral-maxi-dress-in-yellow/211657548-1-yellow", productUrl:"https://www.asos.com/prd/211657548", source:"live-snapshot" },
  { id:"asos-211644135", retailerId:"asos", name:"River Island leopard print pleat front denim dress in brown", brand:"River Island", price:59, colour:"Brown", hex:"#75543f", silhouette:"Structured", neckline:"Boat", sleeve:"Sleeveless", pattern:"Animal", material:"Pure cotton", length:"Mini", sizes:[], imageUrl:"https://images.asos-media.com/products/river-island-leopard-print-pleat-front-denim-dress-in-brown/211644135-1-brown", productUrl:"https://www.asos.com/prd/211644135", source:"live-snapshot" },

  { id:"jigsaw-15210643259558", retailerId:"jigsaw", name:"Iris Leaf Linen Dress | Burgundy", brand:"Jigsaw", price:94, colour:"Red", hex:"#7b1f35", silhouette:"A-line", neckline:"Scoop", sleeve:"Sleeveless", pattern:"Large print", material:"Linen", length:"Maxi", sizes:["UK 6","UK 8","UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0561/7297/0150/files/J51717_RE004_1.jpg?v=1773851672", productUrl:"https://www.jigsaw-online.com/products/iris-leaf-linen-dress-burgundy", source:"live-snapshot" },
  { id:"jigsaw-15172801888422", retailerId:"jigsaw", name:"Cap Sleeve Satin Dress | Pale Green", brand:"Jigsaw", price:68, colour:"Green", hex:"#b7c9ae", silhouette:"Fit and flare", neckline:"Scoop", sleeve:"Cap", pattern:"Solid", material:"Not stated", length:"Maxi", sizes:["UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0561/7297/0150/files/J51410_GN066_1.jpg?v=1773751385", productUrl:"https://www.jigsaw-online.com/products/cap-sleeve-satin-dress-pale-green", source:"live-snapshot" },
  { id:"jigsaw-15210643587238", retailerId:"jigsaw", name:"Sketch Rose Satin Midi Dress | Green", brand:"Jigsaw", price:99, colour:"Green", hex:"#476b4b", silhouette:"Flowy", neckline:"Scoop", sleeve:"3/4", pattern:"Large print", material:"Not stated", length:"Midi", sizes:["UK 6","UK 8","UK 10","UK 16"], imageUrl:"https://cdn.shopify.com/s/files/1/0561/7297/0150/files/J51765_GN000_1.jpg?v=1775577628", productUrl:"https://www.jigsaw-online.com/products/green-56", source:"live-snapshot" },
  { id:"jigsaw-15172800807078", retailerId:"jigsaw", name:"Micro Crepe Cowl Ruched Dress | Blue", brand:"Jigsaw", price:47, colour:"Jewel tones", hex:"#264d70", silhouette:"Flowy", neckline:"Cowl", sleeve:"Long", pattern:"Solid", material:"Not stated", length:"Midi", sizes:[], imageUrl:"https://cdn.shopify.com/s/files/1/0561/7297/0150/files/J51358_BL000_2.jpg?v=1768910099", productUrl:"https://www.jigsaw-online.com/products/microcrepe-cowl-ruched-dress-blue", source:"live-snapshot" },
  { id:"jigsaw-15244983959718", retailerId:"jigsaw", name:"Slub Stripe Cotton Sundress | Mulberry", brand:"Jigsaw", price:72, colour:"Dark pink", hex:"#69364d", silhouette:"Fit and flare", neckline:"Square", sleeve:"Sleeveless", pattern:"Plaid", material:"Pure cotton", length:"Midi", sizes:[], imageUrl:"https://cdn.shopify.com/s/files/1/0561/7297/0150/files/J51852_PU003_1.jpg?v=1774881638", productUrl:"https://www.jigsaw-online.com/products/slub-stripe-sundress-mulberry", source:"live-snapshot" },
  { id:"jigsaw-15172807000230", retailerId:"jigsaw", name:"Iris Cap Sleeve Satin Dress | Green", brand:"Jigsaw", price:91, colour:"Green", hex:"#4d684d", silhouette:"Fit and flare", neckline:"Scoop", sleeve:"Cap", pattern:"Large print", material:"Not stated", length:"Maxi", sizes:["UK 6","UK 8","UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0561/7297/0150/files/J51900_GN000_1.jpg?v=1773751499", productUrl:"https://www.jigsaw-online.com/products/iris-cap-sleeve-satin-dress-green", source:"live-snapshot" },

  { id:"jovonna-14878955602299", retailerId:"jovonna", name:"Moka 2 Dress", brand:"Jovonna London", price:118, colour:"Yellow", hex:"#e4ca57", silhouette:"Flowy", neckline:"Boat", sleeve:"3/4", pattern:"Solid", material:"Linen", length:"Midi", sizes:["UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0402/8940/3034/files/81C6DDFC-1651-453F-ACB1-742F8FFA2A27.jpg?v=1749580589", productUrl:"https://jovonnalondon.com/products/moka-dress-yellow", source:"live-snapshot" },
  { id:"jovonna-14946962768251", retailerId:"jovonna", name:"Seneca Dress Red", brand:"Jovonna London", price:110, colour:"Red", hex:"#a3232e", silhouette:"Fit and flare", neckline:"Boat", sleeve:"Long", pattern:"Large print", material:"Not stated", length:"Midi", sizes:["UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0402/8940/3034/files/IMG_5832.jpg?v=1756220892", productUrl:"https://jovonnalondon.com/products/seneca-dress", source:"live-snapshot" },
  { id:"jovonna-15149008781691", retailerId:"jovonna", name:"Moka Dress White", brand:"Jovonna London", price:118, colour:"White", hex:"#eee9df", silhouette:"Flowy", neckline:"Boat", sleeve:"3/4", pattern:"Solid", material:"Linen", length:"Midi", sizes:["UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0402/8940/3034/files/E35C9B50-7073-4EFA-A7AB-B42A11491F25.jpg?v=1749580655", productUrl:"https://jovonnalondon.com/products/moka-dress-white", source:"live-snapshot" },
  { id:"jovonna-15273596060027", retailerId:"jovonna", name:"Seneca Dress Navy", brand:"Jovonna London", price:110, colour:"Jewel tones", hex:"#1d314b", silhouette:"Fit and flare", neckline:"Boat", sleeve:"Long", pattern:"Large print", material:"Not stated", length:"Midi", sizes:["UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0402/8940/3034/files/IMG_3207.jpg?v=1761302266", productUrl:"https://jovonnalondon.com/products/seneca-dress-blue", source:"live-snapshot" },
  { id:"jovonna-15358445355387", retailerId:"jovonna", name:"Sira Dress", brand:"Jovonna London", price:89, colour:"Camel", hex:"#d6c4a3", silhouette:"Fit and flare", neckline:"Square", sleeve:"Sleeveless", pattern:"Ditsy", material:"Polyester", length:"Midi", sizes:["UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0402/8940/3034/files/DW_250628_Jovonna_31_86744.jpg?v=1773771665", productUrl:"https://jovonnalondon.com/products/sira-dress", source:"live-snapshot" },
  { id:"jovonna-15358446076283", retailerId:"jovonna", name:"Rasia Dress", brand:"Jovonna London", price:105, colour:"Jewel tones", hex:"#172c44", silhouette:"Flowy", neckline:"Scoop", sleeve:"3/4", pattern:"Ditsy", material:"Pure cotton", length:"Midi", sizes:["UK 10"], imageUrl:"https://cdn.shopify.com/s/files/1/0402/8940/3034/files/DW_250628_Jovonna_02_84874.jpg?v=1773771916", productUrl:"https://jovonnalondon.com/products/rasia-dress", source:"live-snapshot" },
];
